- repo: neoclide/coc.nvim
  rev: release
  merged: 0

# Enable nvim native LSP with asyncomplete
# - repo: yami-beta/asyncomplete-omni.vim
#   merged: 0
# - repo: neovim/nvim-lsp
#   merged: 0
# - { repo: prabirshrestha/vim-lsp, if: 0 } # Adds LSP support to vim

  # Disabling asycomplete beceause it is slow compared to CoC
- { repo: prabirshrestha/async.vim, if: 0 }
- { repo: prabirshrestha/asyncomplete.vim, if: 0 }
- { repo: prabirshrestha/asyncomplete-necovim.vim, if: 0 }
- { repo: prabirshrestha/asyncomplete-tags.vim, if: 0 }
- { repo: prabirshrestha/asyncomplete-file.vim, if: 0 }
- { repo: prabirshrestha/asyncomplete-ultisnips.vim, if: 0 }

# Disable vim-lsp since we are using CoC
# Also vim-lsp + asyncomplete have performance issues with vim8
# yami-beta/asyncomplete-omni.vim
- { repo: prabirshrestha/asyncomplete-lsp.vim, if: 0 } # Adds LSP support to asyncomplete
- { repo: prabirshrestha/vim-lsp, if: 0 } # Adds LSP support to vim
- { repo: mattn/vim-lsp-settings, if: 0 } # Adds commands to install language
# servers for vim-lsp

# Disable ale since we are using CoC for linting
- { repo: dense-analysis/ale, if: 0 }

  # Use Polyglot
- repo: sheerun/vim-polyglot
  hook_add: |
    let g:vim_json_syntax_conceal = 1
    let g:vim_markdown_follow_anchor = 1
    let g:html5_event_handler_attributes_complete = 0
    let g:html5_rdfa_attributes_complete = 0
    let g:html5_microdata_attributes_complete = 0
    let g:html5_aria_attributes_complete = 0
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_strikethrough = 1
    let g:vim_markdown_folding_level = 6
    let g:vim_markdown_override_foldtext = 1
    let g:vim_markdown_folding_style_pythonic = 1
    let g:vim_markdown_conceal = 2
    let g:vim_markdown_conceal_code_blocks = 2
    let g:vim_markdown_edit_url_in = 'vsplit'
    let g:vim_markdown_auto_insert_bullets = 1
    let g:vim_markdown_new_list_item_indent = 0
    let g:vim_markdown_toc_autofit = 0
    let g:vim_markdown_fenced_languages = [
      \ 'c++=cpp',
      \ 'viml=vim',
      \ 'bash=sh',
      \ 'ini=dosini',
      \ 'js=javascript',
      \ 'ts=typescript',
      \ 'json=javascript',
      \ 'jsx=javascriptreact',
      \ 'tsx=typescriptreact',
      \ 'docker=Dockerfile',
      \ 'makefile=make',
      \ 'py=python'
      \ ]
    let g:javascript_plugin_jsdoc = 1
    let g:javascript_plugin_flow = 1
    let g:go_gopls_enabled = 0
    let g:go_code_completion_enabled = 0
    let g:go_doc_keywordprg_enabled = 0
    let g:go_def_mapping_enabled = 0
    let g:go_mod_fmt_autosave = 0
    let g:go_highlight_array_whitespace_error = 0
    let g:go_highlight_chan_whitespace_error = 0
    let g:go_highlight_space_tab_error = 0
    let g:go_highlight_trailing_whitespace_error = 0
    let g:go_highlight_extra_types = 1
    let g:go_highlight_build_constraints = 1
    let g:go_highlight_extra_types = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_format_strings = 1
    let g:go_highlight_functions = 1
    let g:go_highlight_function_calls = 1
    let g:go_highlight_function_parameters = 1
    let g:go_highlight_types = 1
    let g:go_highlight_generate_tags = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_string_spellcheck = 0
    let g:go_highlight_variable_declarations = 0
    let g:go_highlight_variable_assignments = 0
    let g:ansible_extra_keywords_highlight = 1
    let g:ansible_template_syntaxes = {
      \   '*.json.j2': 'json',
      \   '*.(ba)?sh.j2': 'sh',
      \   '*.ya?ml.j2': 'yaml',
      \   '*.xml.j2': 'xml',
      \   '*.conf.j2': 'conf',
      \   '*.ini.j2': 'ini'
      \ }
